### ISSUE TITLE
"Unhandled exception" if unlock XY and set one to 1, keep the other at 0 and apply.

### ISSUE THREAD

**Issue by akaStric** [a1xd/rawaccel#42]
Hi,
so as the title says, if i set X to 1 and Y to 0 and apply i get the following error:

![Screenshot_4](https://user-images.githubusercontent.com/13039569/98002715-254a9980-1dee-11eb-959a-494ba8a3cc43.png)

The annoying part is that if i press "Quit", the settings stay saved and it just reappears upon reopening the app. If i press "Continue" it just pops up again, preventing me from reverting the setting.

I tried deleting the settings.json file, thinking it would revert to stock settings - it doesn't. I assume it reads it from the driver if the settings file is missing or something and recreates the file with same invalid settings.

Solution 1 was to replace the settings file with a working one, if one happens to have it, which i did not at first.
Solution 2 was, upon encountering the error, to 
- click "Continue" and
- NOT move the mouse ( as it turns out, the error is triggered by mouse movement )
- Tab to the X or Y with the value 0, change it to 1 for example,
- Tab to "Apply" button and select it with Space
which made it work again.

Not a huge deal, but something you may want to look into for a more graceful error handle in future versions.
Sry for the wall of text :)

Error details:
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at grapher.Models.Calculations.AccelChartData.GetVelocityIndex(Double outVelocityValue)
   at grapher.Models.Calculations.AccelData.CalculateDotsCombinedDiffSens(Int32 x, Int32 y, Double timeInMs, DriverSettings settings)
   at grapher.Models.Charts.ChartState.XYOneGraphState.MakeDots(Int32 x, Int32 y, Double timeInMs)
   at grapher.Models.Mouse.MouseWatcher.OnMouseMove(Int32 x, Int32 y, Double timeInMs)
   at grapher.Models.Mouse.MouseWatcher.ReadMouseMove(Message message)
   at grapher.RawAcceleration.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by a1xd** [comment]
Yeah the gui creates a file from the active config, which can be useful sometimes. It's not so useful in this case though, I'll make sure this is patched in the next release. Thanks!

**Comment by a1xd** [comment]
Fixed in v1.4
